Address removeal of qt6.full
Without this, the following error appears:

    error: qt6.full has been removed. Please use individual packages instead.