Replace vcstool with vcs2l
This is to prevent the following error:

   error: 'vcstool' has been removed, as it has been unmaintained
   upstream since January 2022.