Fix svlangserver build
This fixes errors like:

    ERROR: noBrokenSymlinks: the symlink
    /nix/store/mfpqn6nbag0zpps95za6qikcz4q0a00c-svlangserver-0.4.1+git/lib/node_modules/@imc-trading/svlangserver/node_modules/.bin/acorn
    points to a missing target
    /nix/store/mfpqn6nbag0zpps95za6qikcz4q0a00c-svlangserver-0.4.1+git/lib/node_modules/@imc-trading/svlangserver/node_modules/acorn/bin/acorn