Remove nixpkgs-update
I no longer need it and it breaks `nix flake archive` as follows:

    error:
           … while fetching the input 'github:ryantm/nixpkgs/6a6caacfdd079a0fa249046514480a1c4597d861'

           error: unable to download
           'https://github.com/ryantm/nixpkgs/archive/6a6caacfdd079a0fa249046514480a1c4597d861.tar.gz':
           HTTP error 404