Remove xournal
Due to:

    error: 'xournal' has been removed due to lack of activity upstream
    and depending on gnome2. Consider using 'xournalpp' instead.